service: helloworld

frameworkVersion: '2'

custom:
  env: ${file(./env/${opt:state,'local'}.json)}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    DB_HOST: ${self:custom.env.DB_HOST}
    DB_PORT: ${self:custom.env.DB_PORT}
    DB_USER: ${self:custom.env.DB_USER}
    DB_PASSWD: ${self:custom.env.DB_PASSWORD}
    DB_NAME: ${self:custom.env.DB_NAME}
    REDIS_HOST: ${self:custom.env.REDIS_HOST}
    REDIS_PORT: ${self:custom.env.REDIS_PORT}


functions:
  hello:
    handler: handler.hello
    events:
    - http:
        path: hello/get
        method: get