version: '3.7'
services:
    redis:
      image: redis:6.0.5
      command: redis-server --port 6379 --appendonly yes
      container_name: redis6379
      hostname: redis6379
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - 6379:6379
      volumes:
        - ./db_data/redis/data:/data

    mariadb:
      image: mariadb:10.2.10
      container_name: maria3306
      hostname: maria3306
      restart: always
      labels:
        - "name=mariadb"
        - "mode=standalone"
      environment:
        - MYSQL_ROOT_PASSWORD=mypassword
      ports:
        - 3306:3306
      volumes:
        - ./db_data/mariadb/data:/var/lib/mysql